import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:repllay_app/l10n/l10n.dart';
import 'package:repllay_app/summery/summery.dart';

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return ProviderScope(
      child: MaterialApp(
        theme: FlexThemeData.light(
          colors: const FlexSchemeColor(
            primary: Color(0xff004881),
            primaryContainer: Color(0xffd0e4ff),
            secondary: Color(0xffac3306),
            secondaryContainer: Color(0xffffdbcf),
            tertiary: Color(0xff006875),
            tertiaryContainer: Color(0xff95f0ff),
            appBarColor: Color(0xffffdbcf),
            error: Color(0xffb00020),
          ),
          surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
          blendLevel: 2,
          subThemesData: const FlexSubThemesData(
            blendOnLevel: 10,
            blendOnColors: false,
            blendTextTheme: true,
            useTextTheme: true,
            useM2StyleDividerInM3: true,
            outlinedButtonOutlineSchemeColor: SchemeColor.primary,
            outlinedButtonPressedBorderWidth: 2,
            toggleButtonsBorderSchemeColor: SchemeColor.primary,
            segmentedButtonSchemeColor: SchemeColor.primary,
            segmentedButtonBorderSchemeColor: SchemeColor.primary,
            unselectedToggleIsColored: true,
            sliderValueTinted: true,
            inputDecoratorSchemeColor: SchemeColor.primary,
            inputDecoratorBackgroundAlpha: 21,
            inputDecoratorRadius: 12,
            inputDecoratorUnfocusedHasBorder: false,
            inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
            popupMenuRadius: 6,
            popupMenuElevation: 8,
            alignedDropdown: true,
            useInputDecoratorThemeInDialogs: true,
            drawerIndicatorSchemeColor: SchemeColor.primary,
            bottomNavigationBarMutedUnselectedLabel: false,
            bottomNavigationBarMutedUnselectedIcon: false,
            menuRadius: 6,
            menuElevation: 8,
            menuBarRadius: 0,
            menuBarElevation: 1,
            navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
            navigationBarMutedUnselectedLabel: false,
            navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
            navigationBarMutedUnselectedIcon: false,
            navigationBarIndicatorSchemeColor: SchemeColor.primary,
            navigationBarIndicatorOpacity: 1,
            navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
            navigationRailMutedUnselectedLabel: false,
            navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
            navigationRailMutedUnselectedIcon: false,
            navigationRailIndicatorSchemeColor: SchemeColor.primary,
            navigationRailIndicatorOpacity: 1,
          ),
          visualDensity: FlexColorScheme.comfortablePlatformDensity,
          useMaterial3: true,
          // To use the Playground font, add GoogleFonts package and uncomment
          fontFamily: GoogleFonts.notoSans().fontFamily,
        ),
        darkTheme: FlexThemeData.dark(
          colors: const FlexSchemeColor(
            primary: Color(0xff9fc9ff),
            primaryContainer: Color(0xff00325b),
            secondary: Color(0xffffb59d),
            secondaryContainer: Color(0xff872100),
            tertiary: Color(0xff86d2e1),
            tertiaryContainer: Color(0xff004e59),
            appBarColor: Color(0xff872100),
            error: Color(0xffcf6679),
          ),
          surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
          blendLevel: 8,
          subThemesData: const FlexSubThemesData(
            blendOnLevel: 8,
            blendTextTheme: true,
            useTextTheme: true,
            useM2StyleDividerInM3: true,
            outlinedButtonOutlineSchemeColor: SchemeColor.primary,
            outlinedButtonPressedBorderWidth: 2,
            toggleButtonsBorderSchemeColor: SchemeColor.primary,
            segmentedButtonSchemeColor: SchemeColor.primary,
            segmentedButtonBorderSchemeColor: SchemeColor.primary,
            unselectedToggleIsColored: true,
            sliderValueTinted: true,
            inputDecoratorSchemeColor: SchemeColor.primary,
            inputDecoratorBackgroundAlpha: 43,
            inputDecoratorRadius: 12,
            inputDecoratorUnfocusedHasBorder: false,
            popupMenuRadius: 6,
            popupMenuElevation: 8,
            alignedDropdown: true,
            useInputDecoratorThemeInDialogs: true,
            drawerIndicatorSchemeColor: SchemeColor.primary,
            bottomNavigationBarMutedUnselectedLabel: false,
            bottomNavigationBarMutedUnselectedIcon: false,
            menuRadius: 6,
            menuElevation: 8,
            menuBarRadius: 0,
            menuBarElevation: 1,
            navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
            navigationBarMutedUnselectedLabel: false,
            navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
            navigationBarMutedUnselectedIcon: false,
            navigationBarIndicatorSchemeColor: SchemeColor.primary,
            navigationBarIndicatorOpacity: 1,
            navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
            navigationRailMutedUnselectedLabel: false,
            navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
            navigationRailMutedUnselectedIcon: false,
            navigationRailIndicatorSchemeColor: SchemeColor.primary,
            navigationRailIndicatorOpacity: 1,
          ),
          visualDensity: FlexColorScheme.comfortablePlatformDensity,
          useMaterial3: true,
          fontFamily: GoogleFonts.notoSans().fontFamily,
        ),
        themeMode: ThemeMode.dark,
        localizationsDelegates: AppLocalizations.localizationsDelegates,
        supportedLocales: AppLocalizations.supportedLocales,
        home: const ReplaysPage(),
      ),
    );
  }
}
