name: repllay_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
isar_version: &isar_version 3.1.0+1
dependencies:
  bloc: ^8.1.3
  flex_color_scheme: ^7.3.1
  freezed_annotation: ^2.4.1

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.0
  intl: ^0.18.1
  path_provider: ^2.1.2
  process_run: ^0.14.2
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  watcher: ^1.1.0
  concurrent_queue: ^1.4.0
  webview_windows: ^0.4.0

  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core  
  # pluto_grid: ^8.0.0
  material_table_view: ^4.0.1

dev_dependencies:
  isar_generator: *isar_version
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  json_serializable: ^6.7.1

dependency_overrides: 
  # intl: ^0.18.1

  # riverpod_lint: ^2.3.9
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/bin/
